rm prof* COEF* PRED* SOLRAD* noaa*centerfrq
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof1 prof1
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof2 prof2
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof3 prof3
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof4 prof4
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof5 prof5
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof6 prof6
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof7 prof7
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof8 prof8
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof9 prof9
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof10 prof10
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof11 prof11
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof12 prof12
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof13 prof13
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof14 prof14
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof15 prof15
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof16 prof16
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof17 prof17
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof18 prof18
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof19 prof19
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof20 prof20
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof21 prof21
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof22 prof22
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof23 prof23
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof24 prof24
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof25 prof25
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof26 prof26
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof27 prof27
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof28 prof28
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof29 prof29
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof30 prof30
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof31 prof31
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof32 prof32
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof33 prof33
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof34 prof34
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof35 prof35
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof36 prof36
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof37 prof37
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof38 prof38
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof39 prof39
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof40 prof40
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof41 prof41
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof42 prof42
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof43 prof43
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof44 prof44
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof45 prof45
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof46 prof46
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof47 prof47
ln -s /salsify/users/wehr/HIRS/fmodel/DATA/TestProf/prof48 prof48
ln -s /salsify/users/wehr/HIRS/fmodel/COEF_7.dat COEF_7.dat
ln -s /salsify/users/wehr/HIRS/fmodel/COEF_9.dat COEF_9.dat
ln -s /salsify/users/wehr/HIRS/fmodel/COEF_10.dat COEF_10.dat
ln -s /salsify/users/wehr/HIRS/fmodel/COEF_11.dat COEF_11.dat
ln -s /salsify/users/wehr/HIRS/fmodel/COEF_12.dat COEF_12.dat
ln -s /salsify/users/wehr/HIRS/fmodel/COEF_14.dat COEF_14.dat
ln -s /salsify/users/wehr/HIRS/fmodel/PRED_7.dat PRED_7.dat
ln -s /salsify/users/wehr/HIRS/fmodel/PRED_9.dat PRED_9.dat
ln -s /salsify/users/wehr/HIRS/fmodel/PRED_10.dat PRED_10.dat
ln -s /salsify/users/wehr/HIRS/fmodel/PRED_11.dat PRED_11.dat
ln -s /salsify/users/wehr/HIRS/fmodel/PRED_12.dat PRED_12.dat
ln -s /salsify/users/wehr/HIRS/fmodel/PRED_14.dat PRED_14.dat
ln -s /salsify/users/wehr/HIRS/filter/SOLRAD_7.dat SOLRAD_7.dat
ln -s /salsify/users/wehr/HIRS/filter/SOLRAD_9.dat SOLRAD_9.dat
ln -s /salsify/users/wehr/HIRS/filter/SOLRAD_10.dat SOLRAD_10.dat
ln -s /salsify/users/wehr/HIRS/filter/SOLRAD_11.dat SOLRAD_11.dat
ln -s /salsify/users/wehr/HIRS/filter/SOLRAD_12.dat SOLRAD_12.dat
ln -s /salsify/users/wehr/HIRS/filter/SOLRAD_14.dat SOLRAD_14.dat
ln -s /salsify/users/wehr/HIRS/filter/noaa7.centerfrq noaa7.centerfrq
ln -s /salsify/users/wehr/HIRS/filter/noaa9.centerfrq noaa9.centerfrq
ln -s /salsify/users/wehr/HIRS/filter/noaa10.centerfrq noaa10.centerfrq
ln -s /salsify/users/wehr/HIRS/filter/noaa11.centerfrq noaa11.centerfrq
ln -s /salsify/users/wehr/HIRS/filter/noaa12.centerfrq noaa12.centerfrq
ln -s /salsify/users/wehr/HIRS/filter/noaa14.centerfrq noaa14.centerfrq
