C
C         HDO terms
C         use water terms - but see below
C
C         ----------------------
C         Load up the predictors
C         ----------------------
C
C          -----
C          Fixed (for FWO, FOW, FMW, & FCOW)
C          recall d(u/v) = (v du - u dv)/v^2
C          -----
          IWHICHJAC = 2
 
          TJUNKS_T = 2*TR*TR_T
          TJUNKS_1 = 2*TR*TR_1
          TJUNKS_3 = 2*TR*TR_3

          FIXMUL_T(L)=A_F_T
          FIXMUL_1(L)=A_F_1
          FIXMUL_3(L)=A_F_3
 
           FJACPRED1(IWHICHJAC,1,L)=0
           FJACPRED1(IWHICHJAC,2,L)=0
           FJACPRED1(IWHICHJAC,3,L)=SECANG(L)*TR_1
           FJACPRED1(IWHICHJAC,4,L)=SECANG(L)*TJUNKS_1
           FJACPRED1(IWHICHJAC,5,L)=TR_1
           FJACPRED1(IWHICHJAC,6,L)=TJUNKS_1
           FJACPRED1(IWHICHJAC,7,L)=SECANG(L)*TRZ_1
           FJACPRED1(IWHICHJAC,8,L)=SECANG(L)*(TR*TRZ_1 - TRZ*TR_1)/TR/TR
 
           FJACPRED2(IWHICHJAC,1,L)=FJACPRED1(IWHICHJAC,1,L)
           FJACPRED2(IWHICHJAC,2,L)=FJACPRED1(IWHICHJAC,2,L)
           FJACPRED2(IWHICHJAC,3,L)=FJACPRED1(IWHICHJAC,3,L)
           FJACPRED2(IWHICHJAC,4,L)=FJACPRED1(IWHICHJAC,4,L)
           FJACPRED2(IWHICHJAC,5,L)=FJACPRED1(IWHICHJAC,5,L)
           FJACPRED2(IWHICHJAC,6,L)=FJACPRED1(IWHICHJAC,6,L)
           FJACPRED2(IWHICHJAC,7,L)=FJACPRED1(IWHICHJAC,7,L)
           FJACPRED2(IWHICHJAC,8,L)=FJACPRED1(IWHICHJAC,8,L)
 
           FJACPRED3(IWHICHJAC,1,L)=FJACPRED1(IWHICHJAC,1,L)
           FJACPRED3(IWHICHJAC,2,L)=FJACPRED1(IWHICHJAC,2,L)
           FJACPRED3(IWHICHJAC,3,L)=FJACPRED1(IWHICHJAC,3,L)
           FJACPRED3(IWHICHJAC,4,L)=FJACPRED1(IWHICHJAC,4,L)
           FJACPRED3(IWHICHJAC,5,L)=FJACPRED1(IWHICHJAC,5,L)
           FJACPRED3(IWHICHJAC,6,L)=FJACPRED1(IWHICHJAC,6,L)
           FJACPRED3(IWHICHJAC,7,L)=FJACPRED1(IWHICHJAC,7,L)
           FJACPRED3(IWHICHJAC,8,L)=FJACPRED1(IWHICHJAC,8,L)
 
           FJACPRED4(IWHICHJAC,1,L)=0.0
           FJACPRED4(IWHICHJAC,2,L)=0.0
           FJACPRED4(IWHICHJAC,3,L)=SECANG(L)*TR_1
           FJACPRED4(IWHICHJAC,4,L)=SECANG(L)*TJUNKS_1
           FJACPRED4(IWHICHJAC,5,L)=TR_1
           FJACPRED4(IWHICHJAC,6,L)=TJUNKS_1
           FJACPRED4(IWHICHJAC,7,L)=SECANG(L)*TRZ_1
           FJACPRED4(IWHICHJAC,8,L)=SECANG(L)*SECANG(L)*TRZ_1
           FJACPRED4(IWHICHJAC,9,L)=SECANG(L)*SECANG(L)*TR_1
           FJACPRED4(IWHICHJAC,10,L)=0
           FJACPRED4(IWHICHJAC,11,L)=0
 
C          Fixed predictors for FWO sun bfsw = set5
           FJACPRED5(IWHICHJAC,1,L)=0.0
           FJACPRED5(IWHICHJAC,2,L)=0.0
           FJACPRED5(IWHICHJAC,3,L)=SECANG(L)*TR_1
           FJACPRED5(IWHICHJAC,4,L)=SECANG(L)*TJUNKS_1
           FJACPRED5(IWHICHJAC,5,L)=TR_1
           FJACPRED5(IWHICHJAC,6,L)=TJUNKS_1
           FJACPRED5(IWHICHJAC,7,L)=SECANG(L)*TRZ_1
           FJACPRED5(IWHICHJAC,8,L)=SECANG(L)*(TR*TRZ_1 - TRZ*TR_1)/TR/TR
           FJACPRED5(IWHICHJAC,9,L)=SECANG(L)*SECANG(L)*TR_1
           FJACPRED5(IWHICHJAC,10,L)=0.0
           FJACPRED5(IWHICHJAC,11,L)=TRZ_1
 
c          Fixed predictors for FWO sun mfmw = set6
           FJACPRED6(IWHICHJAC,1,L)=0
           FJACPRED6(IWHICHJAC,2,L)=0
           FJACPRED6(IWHICHJAC,3,L)=SECANG(L)*TR_1
           FJACPRED6(IWHICHJAC,4,L)=SECANG(L)*TJUNKS_1
           FJACPRED6(IWHICHJAC,5,L)=TR_1
           FJACPRED6(IWHICHJAC,6,L)=TJUNKS_1
           FJACPRED6(IWHICHJAC,7,L)=SECANG(L)*TRZ_1
           FJACPRED6(IWHICHJAC,8,L)=0.0
 
C          Fixed predictors for FWO sun mfbw = set7
           FJACPRED7(IWHICHJAC,1,L)=0
           FJACPRED7(IWHICHJAC,2,L)=0
           FJACPRED7(IWHICHJAC,3,L)=SECANG(L)*TR_1
           FJACPRED7(IWHICHJAC,4,L)=SECANG(L)*TJUNKS_1
           FJACPRED7(IWHICHJAC,5,L)=TR_1
           FJACPRED7(IWHICHJAC,6,L)=TJUNKS_1
           FJACPRED7(IWHICHJAC,7,L)=SECANG(L)*TRZ_1
           FJACPRED7(IWHICHJAC,8,L)=0
 
c          -----
C          Ozone
C          -----
           OJUNKA_1=SECANG(L)*A_O_1                     !!! A_O_1 = 0!!!
           OJUNKR_1=SQRT(SECANG(L))*0.5/SQRT(A_O)*A_O_1 !!! A_O_1 = 0!!!
           OJUNKZ_1=(XZ_O*OJUNKA_1 - OJUNKA*XZ_O_1)/XZ_O/XZ_O
           OJUNKZ_1=(XZ_O*OJUNKA_1 - OJUNKA*XZ_O_1)/XZ_O/XZ_O
           OJUNKX_1=SECANG(L)*XZ_O_1

C          Ozone predictors for FWO = set1
           OJACPRED1(IWHICHJAC,1,L)=OJUNKA_1
           OJACPRED1(IWHICHJAC,2,L)=OJUNKR_1
           OJACPRED1(IWHICHJAC,3,L)=OJUNKA_1*DT + OJUNKA*DT_1
           OJACPRED1(IWHICHJAC,4,L)=2*OJUNKA*OJUNKA_1
           OJACPRED1(IWHICHJAC,5,L)=OJUNKR_1*DT + OJUNKR*DT_1

C          ozone predictors for FOW = set2
           OJACPRED2(IWHICHJAC, 1,L)=OJUNKA_1
           OJACPRED2(IWHICHJAC, 2,L)=OJUNKR_1
           OJACPRED2(IWHICHJAC, 3,L)=OJUNKA_1*DT + OJUNKA*DT_1
           OJACPRED2(IWHICHJAC, 4,L)=2*OJUNKA*OJUNKA_1
           OJACPRED2(IWHICHJAC, 5,L)=OJUNKR*DT_1 + OJUNKR_1*DT
           OJACPRED2(IWHICHJAC, 6,L)=OJUNKZ*A_O_1 + OJUNKZ_1*A_O
           OJACPRED2(IWHICHJAC, 7,L)=OJUNKR_1*A_O/XZ_O + OJUNKR*(XZ_O*A_O_1 - A_O*XZ_O_1)/XZ_O/XZ_O 
           OJACPRED2(IWHICHJAC, 8,L)=(OJUNKZ*AZ_O_1 + OJUNKZ_1*AZ_O)
           OJACPRED2(IWHICHJAC, 9,L)=(OJUNKA*0.5/SQRT( OJUNKX )*OJUNKX_1 + OJUNKA_1*SQRT(OJUNKX))
           OJACPRED2(IWHICHJAC,10,L)=(OJUNKA*TAZ_O_1 + OJUNKA_1*TAZ_O)*SECANG(L)

C          There are no ozone predictors for set3 = FMW (the ozone
C          absorption in the region covered by FMW is negligible).
 
C          ozone predictors for FCOW = set4
           OJACPRED4(IWHICHJAC,1,L)=OJUNKA_1
           OJACPRED4(IWHICHJAC,2,L)=OJUNKR_1
           OJACPRED4(IWHICHJAC,3,L)=OJUNKA_1*DT + OJUNKA*DT_1
C
C          ozone predictors for FWO sun bfsw = set5
           OJACPRED5(IWHICHJAC,1,L)=OJUNKA_1
C
C          ozone predictors for FWO sun mfmw = set6
           OJACPRED6(IWHICHJAC,1,L)=OJUNKA_1
C
C          ozone predictors for FWO sun mfbw = set7
           OJACPRED7(IWHICHJAC,1,L)=OJUNKA_1
C
C          -------
C          Methane for FMW = set3
C          -------
           MJUNKA_1=SECANG(L)*A_M_1
           MJUNKR_1=0.5/SQRT(MJUNKA)*MJUNKA_1
           MJUNKZ_1=SECANG(L)*AZ_M_1
           MJACPRED3(IWHICHJAC,1,L)=MJUNKA_1
           MJACPRED3(IWHICHJAC,2,L)=MJUNKR_1
           MJACPRED3(IWHICHJAC,3,L)=MJUNKA_1*DT + MJUNKA*DT_1
           MJACPRED3(IWHICHJAC,4,L)=2*MJUNKA*MJUNKA_1
           MJACPRED3(IWHICHJAC,5,L)=MJUNKA_1*SECANG(L)
           MJACPRED3(IWHICHJAC,6,L)=MJUNKZ_1
           MJACPRED3(IWHICHJAC,7,L)=A_M_1*DT + A_M*DT_1
           MJACPRED3(IWHICHJAC,8,L)=TAZ_M_1*SECANG(L)
           MJACPRED3(IWHICHJAC,9,L)=0.5/SQRT( MJUNKZ )*MJUNKZ_1
C
C          -----
C          Water
C          -----
           WJUNKA_1=SECANG(L)*A_W_1
           WJUNKR_1=SQRT(SECANG(L))*0.5/SQRT(A_W)*A_W_1
           WJUNKS_1=2*WJUNKA*WJUNKA_1
           WJUNKZ_1=WJUNKA_1*A_W/AZ_W + WJUNKA*(AZ_W*A_W_1 - A_W*AZ_W_1)/AZ_W/AZ_W
           WJUNK4_1=(SECANG(L)**0.25)*0.25/(A_W**(0.75))*A_W_1

C          Water predictors for FWO = set1
           WJACPRED1(IWHICHJAC, 1,L)=WJUNKA_1
           WJACPRED1(IWHICHJAC, 2,L)=WJUNKR_1
           WJACPRED1(IWHICHJAC, 3,L)=WJUNKZ_1
           WJACPRED1(IWHICHJAC, 4,L)=WJUNKA_1*DT + WJUNKA*DT_1
           WJACPRED1(IWHICHJAC, 5,L)=WJUNKS_1
           WJACPRED1(IWHICHJAC, 6,L)=WJUNKR_1*DT + WJUNKR*DT_1
           WJACPRED1(IWHICHJAC, 7,L)=WJUNK4_1
           WJACPRED1(IWHICHJAC, 8,L)=(WJUNKR*WJUNKZ_1 - WJUNKZ*WJUNKR_1)/WJUNKR/WJUNKR
           WJACPRED1(IWHICHJAC, 9,L)=WJUNKS*WJUNKA_1 + WJUNKS_1*WJUNKA 
           WJACPRED1(IWHICHJAC,10,L)=A_W_1
           WJACPRED1(IWHICHJAC,11,L)=WJUNKA*DT_1 + WJUNKA_1*DT
           IF (DT .LT. 0) THEN
             WJACPRED1(IWHICHJAC,11,L) = -WJACPRED1(IWHICHJAC,11,L)
           END IF

C          water predictors for FOW = set2
           WJACPRED2(IWHICHJAC, 1,L)=WJUNKA_1
           WJACPRED2(IWHICHJAC, 2,L)=WJUNKR_1
           WJACPRED2(IWHICHJAC, 3,L)=WJUNKA_1*DT + WJUNKA*DT_1
           WJACPRED2(IWHICHJAC, 4,L)=WJUNKA_1*OJUNKX + WJUNKA*OJUNKX_1
           WJACPRED2(IWHICHJAC, 5,L)=WJUNKS_1
           WJACPRED2(IWHICHJAC, 6,L)=WJUNK4_1
           WJACPRED2(IWHICHJAC, 7,L)=WJUNKR_1*DT + WJUNKR*DT_1
           WJACPRED2(IWHICHJAC, 8,L)=WJUNKZ_1
           WJACPRED2(IWHICHJAC, 9,L)=WJUNKA_1*WJUNKS + WJUNKA*WJUNKS_1
           WJACPRED2(IWHICHJAC,10,L)=WJUNKA_1*OJUNKX*OJUNKX + WJUNKA*OJUNKX_1*OJUNKX + WJUNKA*OJUNKX*OJUNKX_1
           WJACPRED2(IWHICHJAC,11,L)=(WJUNKR*WJUNKZ_1 - WJUNKZ*WJUNKR_1)/ WJUNKR/WJUNKR

C          water predictors for FMW = set3
           WJACPRED3(IWHICHJAC, 1,L)=WJUNKA_1
           WJACPRED3(IWHICHJAC, 2,L)=WJUNKR_1
           WJACPRED3(IWHICHJAC, 3,L)=WJUNKZ_1
           WJACPRED3(IWHICHJAC, 4,L)=WJUNKA_1*DT + WJUNKA*DT_1
           WJACPRED3(IWHICHJAC, 5,L)=WJUNKS_1
           WJACPRED3(IWHICHJAC, 6,L)=WJUNKR_1*DT + WJUNKR*DT_1
           WJACPRED3(IWHICHJAC, 7,L)=WJUNK4_1
           WJACPRED3(IWHICHJAC, 8,L)=WJUNKS_1*WJUNKA + WJUNKS*WJUNKA_1
           WJACPRED3(IWHICHJAC, 9,L)=A_W_1
           WJACPRED3(IWHICHJAC,10,L)=(WJUNKR*WJUNKZ_1 - WJUNKZ*WJUNKR_1)/WJUNKR/WJUNKR
           WJACPRED3(IWHICHJAC,11,L)=WJUNKR_1*MJUNKZ + WJUNKR*MJUNKZ_1

c STOPPPED HERE STOPPED HERE XXXXXXX
C          water predictors for FCOW = set4
           WJACPRED4(IWHICHJAC, 1,L)=WJUNKA
           WJACPRED4(IWHICHJAC, 2,L)=A_W
           WJACPRED4(IWHICHJAC, 3,L)=WJUNKR
           WJACPRED4(IWHICHJAC, 4,L)=WJUNKA*DT
           WJACPRED4(IWHICHJAC, 5,L)=WJUNKS
           WJACPRED4(IWHICHJAC, 6,L)=WJUNKR*DT
           WJACPRED4(IWHICHJAC, 7,L)=WJUNK4
           WJACPRED4(IWHICHJAC, 8,L)=WJUNKZ
           WJACPRED4(IWHICHJAC, 9,L)=WJUNKA*SECANG(L)
           WJACPRED4(IWHICHJAC,10,L)=WJUNKS*WJUNKA
           WJACPRED4(IWHICHJAC,11,L)=WJUNKA*AZ_C*SECANG(L)
           WJACPRED4(IWHICHJAC,12,L)=WJUNKZ/WJUNKR
           WJACPRED4(IWHICHJAC,13,L)=WJUNKA*DT*SECANG(L)

C          Water predictors for FWO sun bfsw = set5
           WJACPRED5(IWHICHJAC, 1,L)=WJUNKA
           WJACPRED5(IWHICHJAC, 2,L)=WJUNKA*WJUNKR
           WJACPRED5(IWHICHJAC, 3,L)=WJUNKA*DT

C          Water predictors for FWO sun mfmw = set6
           WJACPRED6(IWHICHJAC, 1,L)=WJUNKA
           WJACPRED6(IWHICHJAC, 2,L)=WJUNKA*WJUNKR
           WJACPRED6(IWHICHJAC, 3,L)=WJUNKA*DT
           WJACPRED6(IWHICHJAC, 4,L)=WJUNKS
           WJACPRED6(IWHICHJAC, 5,L)=WJUNKA*WJUNKR*DT
           WJACPRED6(IWHICHJAC, 6,L)=WJUNKA*WJUNKS
           WJACPRED6(IWHICHJAC, 7,L)=WJUNKA*SECANG(L)

C          Water predictors for FWO sun mfbw = set7
           WJACPRED7(IWHICHJAC, 1,L)=WJUNKA
           WJACPRED7(IWHICHJAC, 2,L)=WJUNKA*WJUNKR
           WJACPRED7(IWHICHJAC, 3,L)=WJUNKA*DT
           WJACPRED7(IWHICHJAC, 4,L)=WJUNKS
           WJACPRED7(IWHICHJAC, 5,L)=WJUNKA*WJUNKR*DT
           WJACPRED7(IWHICHJAC, 6,L)=WJUNKA*WJUNKS
           WJACPRED7(IWHICHJAC, 7,L)=WJUNKA*SECANG(L)
           WJACPRED7(IWHICHJAC, 8,L)=WJUNKZ
           WJACPRED7(IWHICHJAC, 9,L)=WJUNKZ*WJUNKR
           WJACPRED7(IWHICHJAC,10,L)=WJUNKA*WJUNK4
           WJACPRED7(IWHICHJAC,11,L)=WJUNKA*WJUNKZ
           WJACPRED7(IWHICHJAC,12,L)=WJUNKA*A_W
           WJACPRED7(IWHICHJAC,13,L)=WJUNKS/WJUNK4
c STOPPPED HERE STOPPED HERE XXXXXXX

C          ---------------
C          Water continuum (for FWO, FOW, FMW, FCOW)
C          ---------------
           CONJACPRD(IWHICHJAC,1,L)=(TJUNKS*WJUNKA_1 - WJUNKA*TJUNKS_1)/TJUNKS/TJUNKS
           CONJACPRD(IWHICHJAC,2,L)=CONJACPRD(IWHICHJAC,1,L)*A_W/TJUNKS + 
     $                              CONPRD(1,L)*(TJUNKS*A_W_1 - A_W*TJUNKS_1)/TJUNKS/TJUNKS
           CONJACPRD(IWHICHJAC,3,L)=(TR*WJUNKA_1 - WJUNKA*TR_1)/TR/TR
           CONJACPRD(IWHICHJAC,4,L)=CONJACPRD(IWHICHJAC,3,L)*A_W + CONPRD(3,L)*A_W_1
           CONJACPRD(IWHICHJAC,5,L)=CONJACPRD(IWHICHJAC,1,L)*A_W + CONPRD(1,L)*A_W_1
           CONJACPRD(IWHICHJAC,6,L)=(TJUNKS*CONJACPRD(IWHICHJAC,1,L) - CONPRD(1,L)*TJUNKS_1)/TJUNKS/TJUNKS
           CONJACPRD(IWHICHJAC,7,L)=WJUNKA_1
C         print *,'CALPAR CONJACPRD(IWHICHJAC,1,L) = ',L,WJUNKA,TJUNKS,CONJACPRD(IWHICHJAC,1,L)

C          ---------------
C          HDO
C          ---------------
           if (DEBUG) then
             IF(L .EQ. 96) write(6,'(A,X,I4,X,F6.2)') 'calpar: L,HDOFCT ',L,HDOFCT
           endif
           DJUNKA=SECANG(L)*A_W*(1 - HDOFCT)      ! *(1 - HDOFCT)
           DJUNKR=SQRT( DJUNKA )
           DJUNKS=DJUNKA*DJUNKA
           DJUNKZ=DJUNKA*A_W/AZ_W                 ! *(1 - HDOFCT)
           DJUNK4=SQRT( DJUNKR )

           DJACPRED(IWHICHJAC, 1,L)=DJUNKA
           DJACPRED(IWHICHJAC, 2,L)=DJUNKR
           DJACPRED(IWHICHJAC, 3,L)=DJUNKZ
           DJACPRED(IWHICHJAC, 4,L)=DJUNKA*DT
           DJACPRED(IWHICHJAC, 5,L)=DJUNKS
           DJACPRED(IWHICHJAC, 6,L)=DJUNKR*DT
           DJACPRED(IWHICHJAC, 7,L)=DJUNK4
           DJACPRED(IWHICHJAC, 8,L)=DJUNKZ/DJUNKR
           DJACPRED(IWHICHJAC, 9,L)=DJUNKS*DJUNKA
           DJACPRED(IWHICHJAC,10,L)=A_W
           DJACPRED(IWHICHJAC,11,L)=DJUNKA*DT*ABS( DT )

C          ---------------
C          Carbon monoxide for FCOW = set4
C          ---------------
           CJUNKA=SECANG(L)*A_C
           CJUNKR=SQRT( CJUNKA )
           CJUNKS=CJUNKA*CJUNKA
           CJUNKZ=CJUNKA*A_C/AZ_C
           CJACPRED4(IWHICHJAC,1,L)=CJUNKA
           CJACPRED4(IWHICHJAC,2,L)=CJUNKR
           CJACPRED4(IWHICHJAC,3,L)=CJUNKA*DT
           CJACPRED4(IWHICHJAC,4,L)=CJUNKS
           CJACPRED4(IWHICHJAC,5,L)=CJUNKZ
           CJACPRED4(IWHICHJAC,6,L)=CJUNKR*DT
           CJACPRED4(IWHICHJAC,7,L)=SQRT( CJUNKR )
           CJACPRED4(IWHICHJAC,8,L)=CJUNKZ/CJUNKR
           CJACPRED4(IWHICHJAC,9,L)=A_C
           CJACPRED4(IWHICHJAC,10,L)=CJUNKA*SECANG(L)
           CJACPRED4(IWHICHJAC,11,L)=CJUNKR*SECANG(L)
C
C         ---------------
C         trace gas perturbation predictors
C         ---------------
C         The first 4 trace predictors are used by all trace gases
          TRCJACPRD(IWHICHJAC,1,L)=SECANG(L)
          TRCJACPRD(IWHICHJAC,2,L)=TR
          TRCJACPRD(IWHICHJAC,3,L)=SECANG(L)*TR
          TRCJACPRD(IWHICHJAC,4,L)=SECANG(L)*TJUNKS
C         The last 3 trace predictors are only used by N2O
          TRCJACPRD(IWHICHJAC,5,L)=SECANG(L)*SECANG(L)
          TRCJACPRD(IWHICHJAC,6,L)=1.0
          TRCJACPRD(IWHICHJAC,7,L)=SQRT( SECANG(L) )
