C
C         HDO terms
C         use water terms - but see below
C
C         ----------------------
C         Load up the predictors
C         ----------------------
C
C          -----
C          Fixed (for FWO, FOW, FMW, & FCOW)
C          recall d(u/v) = (v du - u dv)/v^2
C          -----
        IF (INTERSECT(3,LISTJ(1:NWANTJ),NWANTJ) .GT. 0) THEN

          IWHICHJAC = 3
 
          TJUNKS_T = 2*TR*TR_T
          TJUNKS_1 = 2*TR*TR_1
          TJUNKS_3 = 2*TR*TR_3

          FIXMUL_T(L)=A_F_T
          FIXMUL_1(L)=A_F_1
          FIXMUL_3(L)=A_F_3
 
           FJACPRED1(IWHICHJAC,1,L)=0
           FJACPRED1(IWHICHJAC,2,L)=0
           FJACPRED1(IWHICHJAC,3,L)=SECANG(L)*TR_3
           FJACPRED1(IWHICHJAC,4,L)=SECANG(L)*TJUNKS_3
           FJACPRED1(IWHICHJAC,5,L)=TR_3
           FJACPRED1(IWHICHJAC,6,L)=TJUNKS_3
           FJACPRED1(IWHICHJAC,7,L)=SECANG(L)*TRZ_3
           FJACPRED1(IWHICHJAC,8,L)=SECANG(L)*(TR*TRZ_3 - TRZ*TR_3)/TR/TR
 
           FJACPRED2(IWHICHJAC,1,L)=FJACPRED1(IWHICHJAC,1,L)
           FJACPRED2(IWHICHJAC,2,L)=FJACPRED1(IWHICHJAC,2,L)
           FJACPRED2(IWHICHJAC,3,L)=FJACPRED1(IWHICHJAC,3,L)
           FJACPRED2(IWHICHJAC,4,L)=FJACPRED1(IWHICHJAC,4,L)
           FJACPRED2(IWHICHJAC,5,L)=FJACPRED1(IWHICHJAC,5,L)
           FJACPRED2(IWHICHJAC,6,L)=FJACPRED1(IWHICHJAC,6,L)
           FJACPRED2(IWHICHJAC,7,L)=FJACPRED1(IWHICHJAC,7,L)
           FJACPRED2(IWHICHJAC,8,L)=FJACPRED1(IWHICHJAC,8,L)
 
           FJACPRED3(IWHICHJAC,1,L)=FJACPRED1(IWHICHJAC,1,L)
           FJACPRED3(IWHICHJAC,2,L)=FJACPRED1(IWHICHJAC,2,L)
           FJACPRED3(IWHICHJAC,3,L)=FJACPRED1(IWHICHJAC,3,L)
           FJACPRED3(IWHICHJAC,4,L)=FJACPRED1(IWHICHJAC,4,L)
           FJACPRED3(IWHICHJAC,5,L)=FJACPRED1(IWHICHJAC,5,L)
           FJACPRED3(IWHICHJAC,6,L)=FJACPRED1(IWHICHJAC,6,L)
           FJACPRED3(IWHICHJAC,7,L)=FJACPRED1(IWHICHJAC,7,L)
           FJACPRED3(IWHICHJAC,8,L)=FJACPRED1(IWHICHJAC,8,L)
 
           FJACPRED4(IWHICHJAC,1,L)=0.0
           FJACPRED4(IWHICHJAC,2,L)=0.0
           FJACPRED4(IWHICHJAC,3,L)=SECANG(L)*TR_3
           FJACPRED4(IWHICHJAC,4,L)=SECANG(L)*TJUNKS_3
           FJACPRED4(IWHICHJAC,5,L)=TR_3
           FJACPRED4(IWHICHJAC,6,L)=TJUNKS_3
           FJACPRED4(IWHICHJAC,7,L)=SECANG(L)*TRZ_3
           FJACPRED4(IWHICHJAC,8,L)=SECANG(L)*SECANG(L)*TRZ_3
           FJACPRED4(IWHICHJAC,9,L)=SECANG(L)*SECANG(L)*TR_3
           FJACPRED4(IWHICHJAC,10,L)=0
           FJACPRED4(IWHICHJAC,11,L)=0
 
C          Fixed predictors for FWO sun bfsw = set5
           FJACPRED5(IWHICHJAC,1,L)=0.0
           FJACPRED5(IWHICHJAC,2,L)=0.0
           FJACPRED5(IWHICHJAC,3,L)=SECANG(L)*TR_3
           FJACPRED5(IWHICHJAC,4,L)=SECANG(L)*TJUNKS_3
           FJACPRED5(IWHICHJAC,5,L)=TR_3
           FJACPRED5(IWHICHJAC,6,L)=TJUNKS_3
           FJACPRED5(IWHICHJAC,7,L)=SECANG(L)*TRZ_3
           FJACPRED5(IWHICHJAC,8,L)=SECANG(L)*(TR*TRZ_3 - TRZ*TR_3)/TR/TR
           FJACPRED5(IWHICHJAC,9,L)=SECANG(L)*SECANG(L)*TR_3
           FJACPRED5(IWHICHJAC,10,L)=0.0
           FJACPRED5(IWHICHJAC,11,L)=TRZ_3
 
c          Fixed predictors for FWO sun mfmw = set6
           FJACPRED6(IWHICHJAC,1,L)=0
           FJACPRED6(IWHICHJAC,2,L)=0
           FJACPRED6(IWHICHJAC,3,L)=SECANG(L)*TR_3
           FJACPRED6(IWHICHJAC,4,L)=SECANG(L)*TJUNKS_3
           FJACPRED6(IWHICHJAC,5,L)=TR_3
           FJACPRED6(IWHICHJAC,6,L)=TJUNKS_3
           FJACPRED6(IWHICHJAC,7,L)=SECANG(L)*TRZ_3
           FJACPRED6(IWHICHJAC,8,L)=0.0
 
C          Fixed predictors for FWO sun mfbw = set7
           FJACPRED7(IWHICHJAC,1,L)=0
           FJACPRED7(IWHICHJAC,2,L)=0
           FJACPRED7(IWHICHJAC,3,L)=SECANG(L)*TR_3
           FJACPRED7(IWHICHJAC,4,L)=SECANG(L)*TJUNKS_3
           FJACPRED7(IWHICHJAC,5,L)=TR_3
           FJACPRED7(IWHICHJAC,6,L)=TJUNKS_3
           FJACPRED7(IWHICHJAC,7,L)=SECANG(L)*TRZ_3
           FJACPRED7(IWHICHJAC,8,L)=0
 
c          -----
C          Ozone
C          -----
           OJUNKA_3=SECANG(L)*A_O_3                     !!! A_O_1 = 0!!!
           OJUNKR_3=SQRT(SECANG(L))*0.5/SQRT(A_O)*A_O_3 !!! A_O_1 = 0!!!
           OJUNKZ_3=(XZ_O*OJUNKA_3 - OJUNKA*XZ_O_3)/XZ_O/XZ_O
           OJUNKX_3=SECANG(L)*XZ_O_3

C          Ozone predictors for FWO = set1
           OJACPRED1(IWHICHJAC,1,L)=OJUNKA_3
           OJACPRED1(IWHICHJAC,2,L)=OJUNKR_3
           OJACPRED1(IWHICHJAC,3,L)=OJUNKA_3*DT + OJUNKA*DT_3
           OJACPRED1(IWHICHJAC,4,L)=2*OJUNKA*OJUNKA_3
           OJACPRED1(IWHICHJAC,5,L)=OJUNKR_3*DT + OJUNKR*DT_3

C          ozone predictors for FOW = set2
           OJACPRED2(IWHICHJAC, 1,L)=OJUNKA_3
           OJACPRED2(IWHICHJAC, 2,L)=OJUNKR_3
           OJACPRED2(IWHICHJAC, 3,L)=OJUNKA_3*DT + OJUNKA*DT_3
           OJACPRED2(IWHICHJAC, 4,L)=2*OJUNKA*OJUNKA_3
           OJACPRED2(IWHICHJAC, 5,L)=OJUNKR*DT_3 + OJUNKR_3*DT
           OJACPRED2(IWHICHJAC, 6,L)=OJUNKZ*A_O_3 + OJUNKZ_3*A_O
           OJACPRED2(IWHICHJAC, 7,L)=OJUNKR_3*A_O/XZ_O + OJUNKR*(XZ_O*A_O_3 - A_O*XZ_O_3)/XZ_O/XZ_O 
           OJACPRED2(IWHICHJAC, 8,L)=(OJUNKZ*AZ_O_3 + OJUNKZ_3*AZ_O)
           OJACPRED2(IWHICHJAC, 9,L)=(OJUNKA*0.5/SQRT( OJUNKX )*OJUNKX_3 + OJUNKA_3*SQRT(OJUNKX))
           OJACPRED2(IWHICHJAC,10,L)=(OJUNKA*TAZ_O_3 + OJUNKA_3*TAZ_O)*SECANG(L)
           !!! see test_o3_10um_preds_predjacs.m
c           write(*,'(I3,X,15(ES12.5))') L,POAMNT(L),ROAMNT(L),SECANG(L),A_O,A_O_3,XZ_O,XZ_O_3,
c     $                          OJUNKA,OJUNKA_3,OJUNKR,OJUNKR_3,OJUNKZ,OJUNKZ_3,OJUNKX,OJUNKX_3

C          There are no ozone predictors for set3 = FMW (the ozone
C          absorption in the region covered by FMW is negligible).
 
C          ozone predictors for FCOW = set4
           OJACPRED4(IWHICHJAC,1,L)=OJUNKA_3
           OJACPRED4(IWHICHJAC,2,L)=OJUNKR_3
           OJACPRED4(IWHICHJAC,3,L)=OJUNKA_3*DT + OJUNKA*DT_3
C
C          ozone predictors for FWO sun bfsw = set5
           OJACPRED5(IWHICHJAC,1,L)=OJUNKA_3
C
C          ozone predictors for FWO sun mfmw = set6
           OJACPRED6(IWHICHJAC,1,L)=OJUNKA_3
C
C          ozone predictors for FWO sun mfbw = set7
           OJACPRED7(IWHICHJAC,1,L)=OJUNKA_3
C
C          -------
C          Methane for FMW = set3
C          -------
           MJUNKA_3=SECANG(L)*A_M_3
           MJUNKR_3=0.5/SQRT(MJUNKA)*MJUNKA_3
           MJUNKZ_3=SECANG(L)*AZ_M_3
           MJACPRED3(IWHICHJAC,1,L)=MJUNKA_3
           MJACPRED3(IWHICHJAC,2,L)=MJUNKR_3
           MJACPRED3(IWHICHJAC,3,L)=MJUNKA_3*DT + MJUNKA*DT_3
           MJACPRED3(IWHICHJAC,4,L)=2*MJUNKA*MJUNKA_3
           MJACPRED3(IWHICHJAC,5,L)=MJUNKA_3*SECANG(L)
           MJACPRED3(IWHICHJAC,6,L)=MJUNKZ_3
           MJACPRED3(IWHICHJAC,7,L)=A_M_3*DT + A_M*DT_3
           MJACPRED3(IWHICHJAC,8,L)=TAZ_M_3*SECANG(L)
           MJACPRED3(IWHICHJAC,9,L)=0.5/SQRT( MJUNKZ )*MJUNKZ_3
C
C          -----
C          Water
C          -----
           WJUNKA_3=SECANG(L)*A_W_3
           WJUNKR_3=SQRT(SECANG(L))*0.5/SQRT(A_W)*A_W_3
           WJUNKS_3=2*WJUNKA*WJUNKA_3
           WJUNKZ_3=WJUNKA_3*A_W/AZ_W + WJUNKA*(AZ_W*A_W_3 - A_W*AZ_W_3)/AZ_W/AZ_W
           WJUNK4_3=(SECANG(L)**0.25)*0.25/(A_W**(0.75))*A_W_3

C          Water predictors for FWO = set1
           WJACPRED1(IWHICHJAC, 1,L)=WJUNKA_3
           WJACPRED1(IWHICHJAC, 2,L)=WJUNKR_3
           WJACPRED1(IWHICHJAC, 3,L)=WJUNKZ_3
           WJACPRED1(IWHICHJAC, 4,L)=WJUNKA_3*DT + WJUNKA*DT_3
           WJACPRED1(IWHICHJAC, 5,L)=WJUNKS_3
           WJACPRED1(IWHICHJAC, 6,L)=WJUNKR_3*DT + WJUNKR*DT_3
           WJACPRED1(IWHICHJAC, 7,L)=WJUNK4_3
           WJACPRED1(IWHICHJAC, 8,L)=(WJUNKR*WJUNKZ_3 - WJUNKZ*WJUNKR_3)/WJUNKR/WJUNKR
           WJACPRED1(IWHICHJAC, 9,L)=WJUNKS*WJUNKA_3 + WJUNKS_3*WJUNKA 
           WJACPRED1(IWHICHJAC,10,L)=A_W_3
           WJACPRED1(IWHICHJAC,11,L)=WJUNKA*DT_3 + WJUNKA_3*DT
           IF (DT .LT. 0) THEN
             WJACPRED1(IWHICHJAC,11,L) = -WJACPRED1(IWHICHJAC,11,L)
           END IF

C          water predictors for FOW = set2
           WJACPRED2(IWHICHJAC, 1,L)=WJUNKA_3
           WJACPRED2(IWHICHJAC, 2,L)=WJUNKR_3
           WJACPRED2(IWHICHJAC, 3,L)=WJUNKA_3*DT + WJUNKA*DT_3
           WJACPRED2(IWHICHJAC, 4,L)=WJUNKA_3*OJUNKX + WJUNKA*OJUNKX_3
           WJACPRED2(IWHICHJAC, 5,L)=WJUNKS_3
           WJACPRED2(IWHICHJAC, 6,L)=WJUNK4_3
           WJACPRED2(IWHICHJAC, 7,L)=WJUNKR_3*DT + WJUNKR*DT_3
           WJACPRED2(IWHICHJAC, 8,L)=WJUNKZ_3
           WJACPRED2(IWHICHJAC, 9,L)=WJUNKA_3*WJUNKS + WJUNKA*WJUNKS_3
           WJACPRED2(IWHICHJAC,10,L)=WJUNKA_3*OJUNKX*OJUNKX + WJUNKA*OJUNKX_3*OJUNKX + WJUNKA*OJUNKX*OJUNKX_3
           WJACPRED2(IWHICHJAC,11,L)=(WJUNKR*WJUNKZ_3 - WJUNKZ*WJUNKR_3)/ WJUNKR/WJUNKR

C          water predictors for FMW = set3
           WJACPRED3(IWHICHJAC, 1,L)=WJUNKA_3
           WJACPRED3(IWHICHJAC, 2,L)=WJUNKR_3
           WJACPRED3(IWHICHJAC, 3,L)=WJUNKZ_3
           WJACPRED3(IWHICHJAC, 4,L)=WJUNKA_3*DT + WJUNKA*DT_3
           WJACPRED3(IWHICHJAC, 5,L)=WJUNKS_3
           WJACPRED3(IWHICHJAC, 6,L)=WJUNKR_3*DT + WJUNKR*DT_3
           WJACPRED3(IWHICHJAC, 7,L)=WJUNK4_3
           WJACPRED3(IWHICHJAC, 8,L)=WJUNKS_3*WJUNKA + WJUNKS*WJUNKA_3
           WJACPRED3(IWHICHJAC, 9,L)=A_W_3
           WJACPRED3(IWHICHJAC,10,L)=(WJUNKR*WJUNKZ_3 - WJUNKZ*WJUNKR_3)/WJUNKR/WJUNKR
           WJACPRED3(IWHICHJAC,11,L)=WJUNKR_3*MJUNKZ + WJUNKR*MJUNKZ_3

C          water predictors for FCOW = set4
           WJACPRED4(IWHICHJAC, 1,L)=WJUNKA_3
           WJACPRED4(IWHICHJAC, 2,L)=A_W_3
           WJACPRED4(IWHICHJAC, 3,L)=WJUNKR_3
           WJACPRED4(IWHICHJAC, 4,L)=WJUNKA_3*DT + WJUNKA*DT_3
           WJACPRED4(IWHICHJAC, 5,L)=WJUNKS_3
           WJACPRED4(IWHICHJAC, 6,L)=WJUNKR_3*DT + WJUNKR*DT_3
           WJACPRED4(IWHICHJAC, 7,L)=WJUNK4_3
           WJACPRED4(IWHICHJAC, 8,L)=WJUNKZ_3
           WJACPRED4(IWHICHJAC, 9,L)=WJUNKA_3*SECANG(L)
           WJACPRED4(IWHICHJAC,10,L)=WJUNKS_3*WJUNKA + WJUNKS*WJUNKA_3
           WJACPRED4(IWHICHJAC,11,L)=WJUNKA_3*AZ_C*SECANG(L) + WJUNKA*AZ_C_3*SECANG(L)
           WJACPRED4(IWHICHJAC,12,L)=(WJUNKR*WJUNKZ_3 - WJUNKZ*WJUNKR_3)/WJUNKZ/WJUNKR
           WJACPRED4(IWHICHJAC,13,L)=WJUNKA_3*DT*SECANG(L) + WJUNKA*DT_3*SECANG(L)

C          Water predictors for FWO sun bfsw = set5
           WJACPRED5(IWHICHJAC, 1,L)=WJUNKA_3
           WJACPRED5(IWHICHJAC, 2,L)=(WJUNKR*WJUNKA_3 - WJUNKA*WJUNKR_3)/WJUNKR/WJUNKR
           WJACPRED5(IWHICHJAC, 3,L)=WJUNKA_3*DT+WJUNKA*DT_3

C          Water predictors for FWO sun mfmw = set6
           WJACPRED6(IWHICHJAC, 1,L)=WJUNKA_3
           WJACPRED6(IWHICHJAC, 2,L)=(WJUNKR*WJUNKA_3 - WJUNKA*WJUNKR_3)/WJUNKR/WJUNKR
           WJACPRED6(IWHICHJAC, 3,L)=WJUNKA_3*DT + WJUNKA*DT_3
           WJACPRED6(IWHICHJAC, 4,L)=WJUNKS_3
           WJACPRED6(IWHICHJAC, 5,L)=WJUNKA_3*WJUNKR*DT + WJUNKA*WJUNKR_3*DT + WJUNKA*WJUNKR*DT_3
           WJACPRED6(IWHICHJAC, 6,L)=WJUNKA_3*WJUNKS + WJUNKA*WJUNKS_3
           WJACPRED6(IWHICHJAC, 7,L)=WJUNKA_3*SECANG(L)

C          Water predictors for FWO sun mfbw = set7
           WJACPRED7(IWHICHJAC, 1,L)=WJUNKA_3
           WJACPRED7(IWHICHJAC, 2,L)=(WJUNKR*WJUNKA_3 - WJUNKA*WJUNKR_3)/WJUNKR/WJUNKR
           WJACPRED7(IWHICHJAC, 3,L)=WJUNKA_3*DT + WJUNKA*DT_3
           WJACPRED7(IWHICHJAC, 4,L)=WJUNKS_3
           WJACPRED7(IWHICHJAC, 5,L)=WJUNKA_3*WJUNKR*DT + WJUNKA*WJUNKR_3*DT + WJUNKA*WJUNKR*DT_3
           WJACPRED7(IWHICHJAC, 6,L)=WJUNKA_3*WJUNKS + WJUNKA*WJUNKS_3
           WJACPRED7(IWHICHJAC, 7,L)=WJUNKA_3*SECANG(L)
           WJACPRED7(IWHICHJAC, 8,L)=WJUNKZ_3
           WJACPRED7(IWHICHJAC, 9,L)=WJUNKZ_3*WJUNKR + WJUNKZ*WJUNKR_3
           WJACPRED7(IWHICHJAC,10,L)=WJUNKA_3*WJUNK4 + WJUNKA*WJUNK4_3
           WJACPRED7(IWHICHJAC,11,L)=WJUNKA_3*WJUNKZ + WJUNKA*WJUNKZ_3
           WJACPRED7(IWHICHJAC,12,L)=WJUNKA_3*A_W + WJUNKA*A_W_3
           WJACPRED7(IWHICHJAC,13,L)=(WJUNK4*WJUNKS_3 -  WJUNKS*WJUNK4_3)/WJUNK4/WJUNK4

C          ---------------
C          Water continuum (for FWO, FOW, FMW, FCOW)
C          ---------------
           CONJACPRD(IWHICHJAC,1,L)=(TJUNKS*WJUNKA_3 - WJUNKA*TJUNKS_3)/TJUNKS/TJUNKS
           CONJACPRD(IWHICHJAC,2,L)=CONJACPRD(IWHICHJAC,1,L)*A_W/TJUNKS + 
     $                              CONPRD(1,L)*(TJUNKS*A_W_3 - A_W*TJUNKS_3)/TJUNKS/TJUNKS
           CONJACPRD(IWHICHJAC,3,L)=(TR*WJUNKA_3 - WJUNKA*TR_3)/TR/TR
           CONJACPRD(IWHICHJAC,4,L)=CONJACPRD(IWHICHJAC,3,L)*A_W + CONPRD(3,L)*A_W_3
           CONJACPRD(IWHICHJAC,5,L)=CONJACPRD(IWHICHJAC,1,L)*A_W + CONPRD(1,L)*A_W_3
           CONJACPRD(IWHICHJAC,6,L)=(TJUNKS*CONJACPRD(IWHICHJAC,1,L) - CONPRD(1,L)*TJUNKS_3)/TJUNKS/TJUNKS
           CONJACPRD(IWHICHJAC,7,L)=WJUNKA_3
C         print *,'CALPAR CONJACPRD(IWHICHJAC,1,L) = ',L,WJUNKA,TJUNKS,CONJACPRD(IWHICHJAC,1,L)

C          ---------------
C          HDO
C          ---------------
           if (DEBUG) then
             IF(L .EQ. 96) write(6,'(A,X,I4,X,F6.2)') 'calpar: L,HDOFCT ',L,HDOFCT
           endif
           DJUNKA_3=SECANG(L)*(A_W_3*(1 - HDOFCT))      ! *(1 - HDOFCT)
           DJUNKR_3=0.5/SQRT( DJUNKA ) * DJUNKA_3
           DJUNKS_3=2*DJUNKA*DJUNKA_3
           DJUNKZ_3=DJUNKA_3*A_W/AZ_W + DJUNKA*(AZ_W*A_W_3 - A_W*AZ_W_3)/AZ_W/AZ_W                 ! *(1 - HDOFCT)
           DJUNK4_3=0.5/SQRT( DJUNKR )*DJUNKR_3

           DJACPRED(IWHICHJAC, 1,L)=DJUNKA_3
           DJACPRED(IWHICHJAC, 2,L)=DJUNKR_3
           DJACPRED(IWHICHJAC, 3,L)=DJUNKZ_3
           DJACPRED(IWHICHJAC, 4,L)=DJUNKA_3*DT + DJUNKA*DT_3
           DJACPRED(IWHICHJAC, 5,L)=DJUNKS_3
           DJACPRED(IWHICHJAC, 6,L)=DJUNKR_3*DT + DJUNKR*DT_3
           DJACPRED(IWHICHJAC, 7,L)=DJUNK4_3
           DJACPRED(IWHICHJAC, 8,L)=(DJUNKR*DJUNKZ_3 - DJUNKZ*DJUNKR_3)/DJUNKR/DJUNKR
           DJACPRED(IWHICHJAC, 9,L)=DJUNKS_3*DJUNKA + DJUNKS*DJUNKA_3
           DJACPRED(IWHICHJAC,10,L)=A_W_3
           DJACPRED(IWHICHJAC,11,L)=DJUNKA_3*DT + DJUNKA*DT_3
           IF (DT .LT. 0) THEN
             DJACPRED(IWHICHJAC,11,L) = -DJACPRED(IWHICHJAC,11,L)
           END IF

C          ---------------
C          Carbon monoxide for FCOW = set4
C          ---------------
           CJUNKA_3=SECANG(L)*A_C_3
           CJUNKR_3=0.5/SQRT( CJUNKA ) * CJUNKA_3
           CJUNKS_3=2*CJUNKA*CJUNKA_3
           CJUNKZ_3=CJUNKA_3*A_C/AZ_C + CJUNKA*(AZ_C*A_C_3 + A_C*AZ_C_3)/AZ_C/AZ_C
           CJACPRED4(IWHICHJAC,1,L)=CJUNKA_3
           CJACPRED4(IWHICHJAC,2,L)=CJUNKR_3
           CJACPRED4(IWHICHJAC,3,L)=CJUNKA_3*DT + CJUNKA*DT_3
           CJACPRED4(IWHICHJAC,4,L)=CJUNKS_3
           CJACPRED4(IWHICHJAC,5,L)=CJUNKZ_3
           CJACPRED4(IWHICHJAC,6,L)=CJUNKR_3*DT + CJUNKR*DT_3
           CJACPRED4(IWHICHJAC,7,L)=0.5/SQRT( CJUNKR )*CJUNKR_3
           CJACPRED4(IWHICHJAC,8,L)=(CJUNKR*CJUNKZ_3 -  CJUNKZ*CJUNKR_3)/CJUNKR/CJUNKR
           CJACPRED4(IWHICHJAC,9,L)=A_C_3
           CJACPRED4(IWHICHJAC,10,L)=CJUNKA_3*SECANG(L)
           CJACPRED4(IWHICHJAC,11,L)=CJUNKR_3*SECANG(L)
C
C         ---------------
C         trace gas perturbation predictors
C         ---------------
C         The first 4 trace predictors are used by all trace gases
          TRCJACPRD(IWHICHJAC,1,L)=0
          TRCJACPRD(IWHICHJAC,2,L)=TR_3
          TRCJACPRD(IWHICHJAC,3,L)=SECANG(L)*TR_3
          TRCJACPRD(IWHICHJAC,4,L)=SECANG(L)*TJUNKS_3
C         The last 3 trace predictors are only used by N2O
          TRCJACPRD(IWHICHJAC,5,L)=0
          TRCJACPRD(IWHICHJAC,6,L)=0
          TRCJACPRD(IWHICHJAC,7,L)=0

        END IF
