C
C         HDO terms
C         use water terms - but see below
C
C         ----------------------
C         Load up the predictors
C         ----------------------
C
C          -----
C          Fixed (for FWO, FOW, FMW, & FCOW)
C          recall d(u/v) = (v du - u dv)/v^2
C          -----
          IWHICHJAC = 1
 
          TJUNKS_T = 2*TR*TR_T
          TJUNKS_1 = 2*TR*TR_1
          TJUNKS_3 = 2*TR*TR_3

          FIXMUL_T(L)=A_F_T
          FIXMUL_1(L)=A_F_1
          FIXMUL_3(L)=A_F_3
 
           FJACPRED1(IWHICHJAC,1,L)=0
           FJACPRED1(IWHICHJAC,2,L)=0
           FJACPRED1(IWHICHJAC,3,L)=SECANG(L)*TR_T
           FJACPRED1(IWHICHJAC,4,L)=SECANG(L)*TJUNKS_T
           FJACPRED1(IWHICHJAC,5,L)=TR_T
           FJACPRED1(IWHICHJAC,6,L)=TJUNKS_T
           FJACPRED1(IWHICHJAC,7,L)=SECANG(L)*TRZ_T
           FJACPRED1(IWHICHJAC,8,L)=SECANG(L)*(TR*TRZ_T - TRZ*TR_T)/TR/TR

           FJACPRED2(IWHICHJAC,1,L)=FJACPRED1(IWHICHJAC,1,L)
           FJACPRED2(IWHICHJAC,2,L)=FJACPRED1(IWHICHJAC,2,L)
           FJACPRED2(IWHICHJAC,3,L)=FJACPRED1(IWHICHJAC,3,L)
           FJACPRED2(IWHICHJAC,4,L)=FJACPRED1(IWHICHJAC,4,L)
           FJACPRED2(IWHICHJAC,5,L)=FJACPRED1(IWHICHJAC,5,L)
           FJACPRED2(IWHICHJAC,6,L)=FJACPRED1(IWHICHJAC,6,L)
           FJACPRED2(IWHICHJAC,7,L)=FJACPRED1(IWHICHJAC,7,L)
           FJACPRED2(IWHICHJAC,8,L)=FJACPRED1(IWHICHJAC,8,L)
 
           FJACPRED3(IWHICHJAC,1,L)=FJACPRED1(IWHICHJAC,1,L)
           FJACPRED3(IWHICHJAC,2,L)=FJACPRED1(IWHICHJAC,2,L)
           FJACPRED3(IWHICHJAC,3,L)=FJACPRED1(IWHICHJAC,3,L)
           FJACPRED3(IWHICHJAC,4,L)=FJACPRED1(IWHICHJAC,4,L)
           FJACPRED3(IWHICHJAC,5,L)=FJACPRED1(IWHICHJAC,5,L)
           FJACPRED3(IWHICHJAC,6,L)=FJACPRED1(IWHICHJAC,6,L)
           FJACPRED3(IWHICHJAC,7,L)=FJACPRED1(IWHICHJAC,7,L)
           FJACPRED3(IWHICHJAC,8,L)=FJACPRED1(IWHICHJAC,8,L)
 
           FJACPRED4(IWHICHJAC,1,L)=0.0
           FJACPRED4(IWHICHJAC,2,L)=0.0
           FJACPRED4(IWHICHJAC,3,L)=SECANG(L)*TR_T
           FJACPRED4(IWHICHJAC,4,L)=SECANG(L)*TJUNKS_T
           FJACPRED4(IWHICHJAC,5,L)=TR_T
           FJACPRED4(IWHICHJAC,6,L)=TJUNKS_T
           FJACPRED4(IWHICHJAC,7,L)=SECANG(L)*TRZ_T
           FJACPRED4(IWHICHJAC,8,L)=SECANG(L)*SECANG(L)*TRZ_T
           FJACPRED4(IWHICHJAC,9,L)=SECANG(L)*SECANG(L)*TR_T
           FJACPRED4(IWHICHJAC,10,L)=0
           FJACPRED4(IWHICHJAC,11,L)=0
 
C          Fixed predictors for FWO sun bfsw = set5
           FJACPRED5(IWHICHJAC,1,L)=0.0
           FJACPRED5(IWHICHJAC,2,L)=0.0
           FJACPRED5(IWHICHJAC,3,L)=SECANG(L)*TR_T
           FJACPRED5(IWHICHJAC,4,L)=SECANG(L)*TJUNKS_T
           FJACPRED5(IWHICHJAC,5,L)=TR_T
           FJACPRED5(IWHICHJAC,6,L)=TJUNKS_T
           FJACPRED5(IWHICHJAC,7,L)=SECANG(L)*TRZ_T
           FJACPRED5(IWHICHJAC,8,L)=SECANG(L)*(TR*TRZ_T - TRZ*TR_T)/TR/TR
           FJACPRED5(IWHICHJAC,9,L)=SECANG(L)*SECANG(L)*TR_T
           FJACPRED5(IWHICHJAC,10,L)=0.0
           FJACPRED5(IWHICHJAC,11,L)=TRZ_T
 
c          Fixed predictors for FWO sun mfmw = set6
           FJACPRED6(IWHICHJAC,1,L)=0
           FJACPRED6(IWHICHJAC,2,L)=0
           FJACPRED6(IWHICHJAC,3,L)=SECANG(L)*TR_T
           FJACPRED6(IWHICHJAC,4,L)=SECANG(L)*TJUNKS_T
           FJACPRED6(IWHICHJAC,5,L)=TR_T
           FJACPRED6(IWHICHJAC,6,L)=TJUNKS_T
           FJACPRED6(IWHICHJAC,7,L)=SECANG(L)*TRZ_T
           FJACPRED6(IWHICHJAC,8,L)=0.0
 
C          Fixed predictors for FWO sun mfbw = set7
           FJACPRED7(IWHICHJAC,1,L)=0
           FJACPRED7(IWHICHJAC,2,L)=0
           FJACPRED7(IWHICHJAC,3,L)=SECANG(L)*TR_T
           FJACPRED7(IWHICHJAC,4,L)=SECANG(L)*TJUNKS_T
           FJACPRED7(IWHICHJAC,5,L)=TR_T
           FJACPRED7(IWHICHJAC,6,L)=TJUNKS_T
           FJACPRED7(IWHICHJAC,7,L)=SECANG(L)*TRZ_T
           FJACPRED7(IWHICHJAC,8,L)=0
 
c          -----
C          Ozone
C          -----
           OJUNKA_T=SECANG(L)*A_O_T                     !!! A_O_T = 0!!!
           OJUNKR_T=SQRT(SECANG(L))*0.5/SQRT(A_O)*A_O_T !!! A_O_T = 0!!!
           OJUNKZ_T=(XZ_O*OJUNKA_T - OJUNKA*XZ_O_T)/XZ_O/XZ_O
           OJUNKX_T=SECANG(L)*XZ_O_T

C          Ozone predictors for FWO = set1
           OJACPRED1(IWHICHJAC,1,L)=OJUNKA_T
           OJACPRED1(IWHICHJAC,2,L)=OJUNKR_T
           OJACPRED1(IWHICHJAC,3,L)=OJUNKA_T*DT + OJUNKA*DT_T
           OJACPRED1(IWHICHJAC,4,L)=2*OJUNKA*OJUNKA_T
           OJACPRED1(IWHICHJAC,5,L)=OJUNKR_T*DT + OJUNKR*DT_T

C          ozone predictors for FOW = set2
           OJACPRED2(IWHICHJAC, 1,L)=OJUNKA_T
           OJACPRED2(IWHICHJAC, 2,L)=OJUNKR_T
           OJACPRED2(IWHICHJAC, 3,L)=OJUNKA_T*DT + OJUNKA*DT_T
           OJACPRED2(IWHICHJAC, 4,L)=2*OJUNKA*OJUNKA_T
           OJACPRED2(IWHICHJAC, 5,L)=OJUNKR*DT_T + OJUNKR_T*DT
           OJACPRED2(IWHICHJAC, 6,L)=OJUNKZ*A_O_T + OJUNKZ_T*A_O
           OJACPRED2(IWHICHJAC, 7,L)=OJUNKR_T*A_O/XZ_O + OJUNKR*(XZ_O*A_O_T - A_O*XZ_O_T)/XZ_O/XZ_O 
           OJACPRED2(IWHICHJAC, 8,L)=(OJUNKZ*AZ_O_T + OJUNKZ_T*AZ_O)
           OJACPRED2(IWHICHJAC, 9,L)=(OJUNKA*0.5/SQRT( OJUNKX )*OJUNKX_T + OJUNKA_T*SQRT(OJUNKX))
           OJACPRED2(IWHICHJAC,10,L)=(OJUNKA*TAZ_O_T + OJUNKA_T*TAZ_O)*SECANG(L)

C          There are no ozone predictors for set3 = FMW (the ozone
C          absorption in the region covered by FMW is negligible).
 
C          ozone predictors for FCOW = set4
           OJACPRED4(IWHICHJAC,1,L)=OJUNKA_T
           OJACPRED4(IWHICHJAC,2,L)=OJUNKR_T
           OJACPRED4(IWHICHJAC,3,L)=OJUNKA_T*DT + OJUNKA*DT_T
C
C          ozone predictors for FWO sun bfsw = set5
           OJACPRED5(IWHICHJAC,1,L)=OJUNKA_T
C
C          ozone predictors for FWO sun mfmw = set6
           OJACPRED6(IWHICHJAC,1,L)=OJUNKA_T
C
C          ozone predictors for FWO sun mfbw = set7
           OJACPRED7(IWHICHJAC,1,L)=OJUNKA_T
C
C          -------
C          Methane for FMW = set3
C          -------
           MJUNKA_T=SECANG(L)*A_M_T
           MJUNKR_T=0.5/SQRT(MJUNKA)*MJUNKA_T
           MJUNKZ_T=SECANG(L)*AZ_M_T
           MJACPRED3(IWHICHJAC,1,L)=MJUNKA_T
           MJACPRED3(IWHICHJAC,2,L)=MJUNKR_T
           MJACPRED3(IWHICHJAC,3,L)=MJUNKA_T*DT + MJUNKA*DT_T
           MJACPRED3(IWHICHJAC,4,L)=2*MJUNKA*MJUNKA_T
           MJACPRED3(IWHICHJAC,5,L)=MJUNKA_T*SECANG(L)
           MJACPRED3(IWHICHJAC,6,L)=MJUNKZ_T
           MJACPRED3(IWHICHJAC,7,L)=A_M_T*DT + A_M*DT_T
           MJACPRED3(IWHICHJAC,8,L)=TAZ_M_T*SECANG(L)
           MJACPRED3(IWHICHJAC,9,L)=0.5/SQRT( MJUNKZ )*MJUNKZ_T
C
C
C          -----
C          Water
C          -----
           WJUNKA_T=SECANG(L)*A_W_T
           WJUNKR_T=SQRT(SECANG(L))*0.5/SQRT(A_W)*A_W_T
           WJUNKS_T=2*WJUNKA*WJUNKA_T
           WJUNKZ_T=WJUNKA_T*A_W/AZ_W + WJUNKA*(AZ_W*A_W_T - A_W*AZ_W_T)/AZ_W/AZ_W
           WJUNK4_T=(SECANG(L)**0.25)*0.25/(A_W**(0.75))*A_W_T

C          Water predictors for FWO = set1
           WJACPRED1(IWHICHJAC, 1,L)=WJUNKA_T
           WJACPRED1(IWHICHJAC, 2,L)=WJUNKR_T
           WJACPRED1(IWHICHJAC, 3,L)=WJUNKZ_T
           WJACPRED1(IWHICHJAC, 4,L)=WJUNKA_T*DT + WJUNKA*DT_T
           WJACPRED1(IWHICHJAC, 5,L)=WJUNKS_T
           WJACPRED1(IWHICHJAC, 6,L)=WJUNKR_T*DT + WJUNKR*DT_T
           WJACPRED1(IWHICHJAC, 7,L)=WJUNK4_T
           WJACPRED1(IWHICHJAC, 8,L)=(WJUNKR*WJUNKZ_T - WJUNKZ*WJUNKR_T)/WJUNKR/WJUNKR
           WJACPRED1(IWHICHJAC, 9,L)=WJUNKS*WJUNKA_T + WJUNKS_T*WJUNKA 
           WJACPRED1(IWHICHJAC,10,L)=A_W_T
           WJACPRED1(IWHICHJAC,11,L)=WJUNKA*DT_T + WJUNKA_T*DT
           IF (DT .LT. 0) THEN
             WJACPRED1(IWHICHJAC,11,L) = -WJACPRED1(IWHICHJAC,11,L)
           END IF

C          water predictors for FOW = set2
           WJACPRED2(IWHICHJAC, 1,L)=WJUNKA_T
           WJACPRED2(IWHICHJAC, 2,L)=WJUNKR_T
           WJACPRED2(IWHICHJAC, 3,L)=WJUNKA_T*DT + WJUNKA*DT_T
           WJACPRED2(IWHICHJAC, 4,L)=WJUNKA_T*OJUNKX + WJUNKA*OJUNKX_T
           WJACPRED2(IWHICHJAC, 5,L)=WJUNKS_T
           WJACPRED2(IWHICHJAC, 6,L)=WJUNK4_T
           WJACPRED2(IWHICHJAC, 7,L)=WJUNKR_T*DT + WJUNKR*DT_T
           WJACPRED2(IWHICHJAC, 8,L)=WJUNKZ_T
           WJACPRED2(IWHICHJAC, 9,L)=WJUNKA_T*WJUNKS + WJUNKA*WJUNKS_T
           WJACPRED2(IWHICHJAC,10,L)=WJUNKA_T*OJUNKX*OJUNKX + WJUNKA*OJUNKX_T*OJUNKX + WJUNKA*OJUNKX*OJUNKX_T
           WJACPRED2(IWHICHJAC,11,L)=(WJUNKR*WJUNKZ_T - WJUNKZ*WJUNKR_T)/ WJUNKR/WJUNKR

C          water predictors for FMW = set3
           WJACPRED3(IWHICHJAC, 1,L)=WJUNKA_T
           WJACPRED3(IWHICHJAC, 2,L)=WJUNKR_T
           WJACPRED3(IWHICHJAC, 3,L)=WJUNKZ_T
           WJACPRED3(IWHICHJAC, 4,L)=WJUNKA_T*DT + WJUNKA*DT_T
           WJACPRED3(IWHICHJAC, 5,L)=WJUNKS_T
           WJACPRED3(IWHICHJAC, 6,L)=WJUNKR_T*DT + WJUNKR*DT_T
           WJACPRED3(IWHICHJAC, 7,L)=WJUNK4_T
           WJACPRED3(IWHICHJAC, 8,L)=WJUNKS_T*WJUNKA + WJUNKS*WJUNKA_T
           WJACPRED3(IWHICHJAC, 9,L)=A_W_T
           WJACPRED3(IWHICHJAC,10,L)=(WJUNKR*WJUNKZ_T - WJUNKZ*WJUNKR_T)/WJUNKR/WJUNKR
           WJACPRED3(IWHICHJAC,11,L)=WJUNKR_T*MJUNKZ + WJUNKR*MJUNKZ_T

C          water predictors for FCOW = set4
           WJACPRED4(IWHICHJAC, 1,L)=WJUNKA_T
           WJACPRED4(IWHICHJAC, 2,L)=A_W_T
           WJACPRED4(IWHICHJAC, 3,L)=WJUNKR_T
           WJACPRED4(IWHICHJAC, 4,L)=WJUNKA_T*DT + WJUNKA*DT_T
           WJACPRED4(IWHICHJAC, 5,L)=WJUNKS_T
           WJACPRED4(IWHICHJAC, 6,L)=WJUNKR_T*DT + WJUNKR*DT_T
           WJACPRED4(IWHICHJAC, 7,L)=WJUNK4_T
           WJACPRED4(IWHICHJAC, 8,L)=WJUNKZ_T
           WJACPRED4(IWHICHJAC, 9,L)=WJUNKA_T*SECANG(L)
           WJACPRED4(IWHICHJAC,10,L)=WJUNKS_T*WJUNKA + WJUNKS*WJUNKA_T
           WJACPRED4(IWHICHJAC,11,L)=WJUNKA_T*AZ_C*SECANG(L) + WJUNKA*AZ_C_T*SECANG(L)
           WJACPRED4(IWHICHJAC,12,L)=(WJUNKR*WJUNKZ_T - WJUNKZ*WJUNKR_T)/WJUNKZ/WJUNKR
           WJACPRED4(IWHICHJAC,13,L)=WJUNKA_T*DT*SECANG(L) + WJUNKA*DT_T*SECANG(L)

C          Water predictors for FWO sun bfsw = set5
           WJACPRED5(IWHICHJAC, 1,L)=WJUNKA_T
           WJACPRED5(IWHICHJAC, 2,L)=(WJUNKR*WJUNKA_T - WJUNKA*WJUNKR_T)/WJUNKR/WJUNKR
           WJACPRED5(IWHICHJAC, 3,L)=WJUNKA_T*DT+WJUNKA*DT_T

C          Water predictors for FWO sun mfmw = set6
           WJACPRED6(IWHICHJAC, 1,L)=WJUNKA_T
           WJACPRED6(IWHICHJAC, 2,L)=(WJUNKR*WJUNKA_T - WJUNKA*WJUNKR_T)/WJUNKR/WJUNKR
           WJACPRED6(IWHICHJAC, 3,L)=WJUNKA_T*DT + WJUNKA*DT_T
           WJACPRED6(IWHICHJAC, 4,L)=WJUNKS_T
           WJACPRED6(IWHICHJAC, 5,L)=WJUNKA_T*WJUNKR*DT + WJUNKA*WJUNKR_T*DT + WJUNKA*WJUNKR*DT_T
           WJACPRED6(IWHICHJAC, 6,L)=WJUNKA_T*WJUNKS + WJUNKA*WJUNKS_T
           WJACPRED6(IWHICHJAC, 7,L)=WJUNKA_T*SECANG(L)

C          Water predictors for FWO sun mfbw = set7
           WJACPRED7(IWHICHJAC, 1,L)=WJUNKA_T
           WJACPRED7(IWHICHJAC, 2,L)=(WJUNKR*WJUNKA_T - WJUNKA*WJUNKR_T)/WJUNKR/WJUNKR
           WJACPRED7(IWHICHJAC, 3,L)=WJUNKA_T*DT + WJUNKA*DT_T
           WJACPRED7(IWHICHJAC, 4,L)=WJUNKS_T
           WJACPRED7(IWHICHJAC, 5,L)=WJUNKA_T*WJUNKR*DT + WJUNKA*WJUNKR_T*DT + WJUNKA*WJUNKR*DT_T
           WJACPRED7(IWHICHJAC, 6,L)=WJUNKA_T*WJUNKS + WJUNKA*WJUNKS_T
           WJACPRED7(IWHICHJAC, 7,L)=WJUNKA_T*SECANG(L)
           WJACPRED7(IWHICHJAC, 8,L)=WJUNKZ_T
           WJACPRED7(IWHICHJAC, 9,L)=WJUNKZ_T*WJUNKR + WJUNKZ*WJUNKR_T
           WJACPRED7(IWHICHJAC,10,L)=WJUNKA_T*WJUNK4 + WJUNKA*WJUNK4_T
           WJACPRED7(IWHICHJAC,11,L)=WJUNKA_T*WJUNKZ + WJUNKA*WJUNKZ_T
           WJACPRED7(IWHICHJAC,12,L)=WJUNKA_T*A_W + WJUNKA*A_W_T
           WJACPRED7(IWHICHJAC,13,L)=(WJUNK4*WJUNKS_T -  WJUNKS*WJUNK4_T)/WJUNK4/WJUNK4

C          ---------------
C          Water continuum (for FWO, FOW, FMW, FCOW)
C          ---------------
           CONJACPRD(IWHICHJAC,1,L)=(TJUNKS*WJUNKA_T - WJUNKA*TJUNKS_T)/TJUNKS/TJUNKS
           CONJACPRD(IWHICHJAC,2,L)=CONJACPRD(IWHICHJAC,1,L)*A_W/TJUNKS + 
     $                              CONPRD(IWHICHJAC,L)*(TJUNKS*A_W_T - A_W*TJUNKS_T)/TJUNKS/TJUNKS
           CONJACPRD(IWHICHJAC,3,L)=(TR*WJUNKA_T - WJUNKA*TR_T)/TR/TR
           CONJACPRD(IWHICHJAC,4,L)=CONJACPRD(IWHICHJAC,3,L)*A_W + CONPRD(3,L)*A_W_T
           CONJACPRD(IWHICHJAC,5,L)=CONJACPRD(IWHICHJAC,1,L)*A_W + CONPRD(IWHICHJAC,L)*A_W_T
           CONJACPRD(IWHICHJAC,6,L)=(TJUNKS*CONJACPRD(IWHICHJAC,1,L) - CONPRD(IWHICHJAC,L)*TJUNKS_T)/TJUNKS/TJUNKS
           CONJACPRD(IWHICHJAC,7,L)=WJUNKA_T
C         print *,'CALPAR CONJACPRD(IWHICHJAC,1,L) = ',L,WJUNKA,TJUNKS,CONJACPRD(IWHICHJAC,1,L)

C          ---------------
C          HDO
C          ---------------
           if (DEBUG) then
             IF(L .EQ. 96) write(6,'(A,X,I4,X,F6.2)') 'calpar: L,HDOFCT ',L,HDOFCT
           endif
           DJUNKA_T=SECANG(L)*A_W_T*(1 - HDOFCT)      ! *(1 - HDOFCT)
           DJUNKR_T=0.5/SQRT( DJUNKA ) * DJUNKA_T
           DJUNKS_T=2*DJUNKA*DJUNKA_T
           DJUNKZ_T=DJUNKA_T*A_W/AZ_W + DJUNKA*(AZ_W*A_W_T - A_W*AZ_W_T)/AZ_W/AZ_W                 ! *(1 - HDOFCT)
           DJUNK4_T=0.5/SQRT( DJUNKR )*DJUNKR_T

           DJACPRED(IWHICHJAC, 1,L)=DJUNKA_T
           DJACPRED(IWHICHJAC, 2,L)=DJUNKR_T
           DJACPRED(IWHICHJAC, 3,L)=DJUNKZ_T
           DJACPRED(IWHICHJAC, 4,L)=DJUNKA_T*DT + DJUNKA*DT_T
           DJACPRED(IWHICHJAC, 5,L)=DJUNKS_T
           DJACPRED(IWHICHJAC, 6,L)=DJUNKR_T*DT + DJUNKR*DT_T
           DJACPRED(IWHICHJAC, 7,L)=DJUNK4_T
           DJACPRED(IWHICHJAC, 8,L)=(DJUNKR*DJUNKZ_T - DJUNKZ*DJUNKR_T)/DJUNKR/DJUNKR
           DJACPRED(IWHICHJAC, 9,L)=DJUNKS_T*DJUNKA + DJUNKS*DJUNKA_T
           DJACPRED(IWHICHJAC,10,L)=A_W_T
           DJACPRED(IWHICHJAC,11,L)=DJUNKA_T*DT + DJUNKA*DT_T
           IF (DT .LT. 0) THEN
             DJACPRED(IWHICHJAC,11,L) = -DJACPRED(IWHICHJAC,11,L)
           END IF

C          ---------------
C          Carbon monoxide for FCOW = set4
C          ---------------
           CJUNKA=SECANG(L)*A_C_T
           CJUNKR=0.5/SQRT( CJUNKA ) * CJUNKA_T
           CJUNKS=2*CJUNKA*CJUNKA_T
           CJUNKZ=CJUNKA_T*A_C/AZ_C + CJUNKA*(AZ_C*A_C_T + A_C*AZ_C_T)/AZ_C/AZ_C
           CJACPRED4(IWHICHJAC,1,L)=CJUNKA_T
           CJACPRED4(IWHICHJAC,2,L)=CJUNKR_T
           CJACPRED4(IWHICHJAC,3,L)=CJUNKA_T*DT + CJUNKA*DT_T
           CJACPRED4(IWHICHJAC,4,L)=CJUNKS_T
           CJACPRED4(IWHICHJAC,5,L)=CJUNKZ_T
           CJACPRED4(IWHICHJAC,6,L)=CJUNKR_T*DT + CJUNKR*DT_T
           CJACPRED4(IWHICHJAC,7,L)=0.5/SQRT( CJUNKR )*CJUNKR_T
           CJACPRED4(IWHICHJAC,8,L)=(CJUNKR*CJUNKZ_T -  CJUNKZ*CJUNKR_T)/CJUNKR/CJUNKR
           CJACPRED4(IWHICHJAC,9,L)=A_C_T
           CJACPRED4(IWHICHJAC,10,L)=CJUNKA_T*SECANG(L)
           CJACPRED4(IWHICHJAC,11,L)=CJUNKR_T*SECANG(L)
C
C         ---------------
C         trace gas perturbation predictors
C         ---------------
C         The first 4 trace predictors are used by all trace gases
          TRCJACPRD(IWHICHJAC,1,L)=0
          TRCJACPRD(IWHICHJAC,2,L)=TR_T
          TRCJACPRD(IWHICHJAC,3,L)=SECANG(L)*TR_T
          TRCJACPRD(IWHICHJAC,4,L)=SECANG(L)*TJUNKS_T
C         The last 3 trace predictors are only used by N2O
          TRCJACPRD(IWHICHJAC,5,L)=0
          TRCJACPRD(IWHICHJAC,6,L)=0.0
          TRCJACPRD(IWHICHJAC,7,L)=0
