MODULE SELECT_SPECIES

	TYPE DO_SPECIES_LOGICAL_ARRAY_TYPE
		LOGICAL :: DO_TEMPERATURE
		LOGICAL :: DO_H2O
		LOGICAL :: DO_CO2
		LOGICAL :: DO_O3
		LOGICAL :: DO_CO
		LOGICAL :: DO_CH4
		LOGICAL :: DO_SO2
		LOGICAL :: DO_HNO3
		LOGICAL :: DO_N2O
		LOGICAL :: DO_TSUR  ! not implemented specifically for TSUR
		LOGICAL :: DO_ALL
		LOGICAL :: DO_ALL_NO_SAVE
		LOGICAL :: DO_NONE
	END TYPE DO_SPECIES_LOGICAL_ARRAY_TYPE


CONTAINS

	FUNCTION SELECT_SPECIES__DETERMINE_DO_SPECIES_ARRAY(SELECTED_SPECIES) RESULT(DO_SPECIES)
	
		CHARACTER (LEN = *) :: SELECTED_SPECIES
		TYPE (DO_SPECIES_LOGICAL_ARRAY_TYPE) :: DO_SPECIES

		! Trimmed character string
		CHARACTER (LEN = LEN_TRIM(SELECTED_SPECIES)) :: SELECTED_SPECIES_TRIMMED

		SELECTED_SPECIES_TRIMMED = TRIM(SELECTED_SPECIES)
		
		CONSTITUENT: SELECT CASE (SELECTED_SPECIES_TRIMMED)
			CASE ("ALL")
				DO_SPECIES % DO_TEMPERATURE = .TRUE.
				DO_SPECIES % DO_H2O 		= .TRUE.
				DO_SPECIES % DO_CO2 		= .TRUE.
				DO_SPECIES % DO_O3 			= .TRUE.
				DO_SPECIES % DO_CO 			= .TRUE.
				DO_SPECIES % DO_CH4 		= .TRUE.
				DO_SPECIES % DO_SO2 		= .TRUE.
				DO_SPECIES % DO_HNO3 		= .TRUE.
				DO_SPECIES % DO_N2O 		= .TRUE.
				DO_SPECIES % DO_TSUR 		= .TRUE.
				DO_SPECIES % DO_ALL 		= .TRUE.			
				DO_SPECIES % DO_NONE 		= .FALSE.			
			CASE ("ALL_NO_SAVE") ! Does all the predictors and OD's, but does not save them
				DO_SPECIES % DO_TEMPERATURE = .TRUE.
				DO_SPECIES % DO_H2O 		= .TRUE.
				DO_SPECIES % DO_CO2 		= .TRUE.
				DO_SPECIES % DO_O3 			= .TRUE.
				DO_SPECIES % DO_CO 			= .TRUE.
				DO_SPECIES % DO_CH4 		= .TRUE.
				DO_SPECIES % DO_SO2 		= .TRUE.
				DO_SPECIES % DO_HNO3 		= .TRUE.
				DO_SPECIES % DO_N2O 		= .TRUE.
				DO_SPECIES % DO_TSUR 		= .TRUE.
				DO_SPECIES % DO_ALL 		= .FALSE.			
				DO_SPECIES % DO_NONE 		= .FALSE.			
			CASE ("TEMPERATURE")
				DO_SPECIES % DO_TEMPERATURE = .TRUE.
				DO_SPECIES % DO_H2O 		= .TRUE.
				DO_SPECIES % DO_CO2 		= .TRUE.
				DO_SPECIES % DO_O3 			= .TRUE.
				DO_SPECIES % DO_CO 			= .TRUE.
				DO_SPECIES % DO_CH4 		= .TRUE.
				DO_SPECIES % DO_SO2 		= .TRUE.
				DO_SPECIES % DO_HNO3 		= .TRUE.
				DO_SPECIES % DO_N2O 		= .TRUE.
				DO_SPECIES % DO_TSUR 		= .TRUE.
				DO_SPECIES % DO_ALL 		= .FALSE.			
				DO_SPECIES % DO_NONE 		= .FALSE.			
			CASE ("H2O")  ! H2O affects FIXMUL, so have to recalcuate MLT's for trace gases
				DO_SPECIES % DO_TEMPERATURE = .TRUE.
				DO_SPECIES % DO_H2O 		= .TRUE.
				DO_SPECIES % DO_CO2 		= .TRUE.
				DO_SPECIES % DO_O3 			= .TRUE.
				DO_SPECIES % DO_CO 			= .FALSE.
				DO_SPECIES % DO_CH4 		= .FALSE.
				DO_SPECIES % DO_SO2 		= .TRUE.
				DO_SPECIES % DO_HNO3		= .TRUE.
				DO_SPECIES % DO_N2O 		= .TRUE.
				DO_SPECIES % DO_TSUR 		= .FALSE.
				DO_SPECIES % DO_ALL 		= .FALSE.			
				DO_SPECIES % DO_NONE 		= .FALSE.			
			CASE ("CO2")
				DO_SPECIES % DO_TEMPERATURE = .FALSE.
				DO_SPECIES % DO_H2O 		= .FALSE.
				DO_SPECIES % DO_CO2 		= .TRUE.
				DO_SPECIES % DO_O3 			= .FALSE.
				DO_SPECIES % DO_CO 			= .FALSE.
				DO_SPECIES % DO_CH4 		= .FALSE.
				DO_SPECIES % DO_SO2 		= .FALSE.
				DO_SPECIES % DO_HNO3		= .FALSE.
				DO_SPECIES % DO_N2O 		= .FALSE.
				DO_SPECIES % DO_TSUR 		= .FALSE.
				DO_SPECIES % DO_ALL 		= .FALSE.			
				DO_SPECIES % DO_NONE 		= .FALSE.			
			CASE ("O3")
				DO_SPECIES % DO_TEMPERATURE = .FALSE.
				DO_SPECIES % DO_H2O 		= .FALSE.
				DO_SPECIES % DO_CO2 		= .FALSE.
				DO_SPECIES % DO_O3 			= .TRUE.
				DO_SPECIES % DO_CO 			= .FALSE.
				DO_SPECIES % DO_CH4 		= .FALSE.
				DO_SPECIES % DO_SO2 		= .FALSE.
				DO_SPECIES % DO_HNO3		= .FALSE.
				DO_SPECIES % DO_N2O 		= .FALSE.
				DO_SPECIES % DO_TSUR 		= .FALSE.
				DO_SPECIES % DO_ALL 		= .FALSE.			
				DO_SPECIES % DO_NONE 		= .FALSE.			
			CASE ("CO")
				DO_SPECIES % DO_TEMPERATURE = .FALSE.
				DO_SPECIES % DO_H2O 		= .FALSE.
				DO_SPECIES % DO_CO2 		= .FALSE.
				DO_SPECIES % DO_O3 			= .FALSE.
				DO_SPECIES % DO_CO 			= .TRUE.
				DO_SPECIES % DO_CH4 		= .FALSE.
				DO_SPECIES % DO_SO2 		= .FALSE.
				DO_SPECIES % DO_HNO3		= .FALSE.
				DO_SPECIES % DO_N2O 		= .FALSE.
				DO_SPECIES % DO_TSUR 		= .FALSE.
				DO_SPECIES % DO_ALL 		= .FALSE.			
				DO_SPECIES % DO_NONE 		= .FALSE.			
			CASE ("CH4")
				DO_SPECIES % DO_TEMPERATURE = .FALSE.
				DO_SPECIES % DO_H2O 		= .FALSE.
				DO_SPECIES % DO_CO2 		= .FALSE.
				DO_SPECIES % DO_O3 			= .FALSE.
				DO_SPECIES % DO_CO 			= .FALSE.
				DO_SPECIES % DO_CH4 		= .TRUE.
				DO_SPECIES % DO_SO2 		= .FALSE.
				DO_SPECIES % DO_HNO3		= .FALSE.
				DO_SPECIES % DO_N2O 		= .FALSE.
				DO_SPECIES % DO_TSUR 		= .FALSE.
				DO_SPECIES % DO_ALL 		= .FALSE.			
				DO_SPECIES % DO_NONE 		= .FALSE.			
			CASE ("SO2")
				DO_SPECIES % DO_TEMPERATURE = .FALSE.
				DO_SPECIES % DO_H2O 		= .FALSE.
				DO_SPECIES % DO_CO2 		= .FALSE.
				DO_SPECIES % DO_O3 			= .FALSE.
				DO_SPECIES % DO_CO 			= .FALSE.
				DO_SPECIES % DO_CH4 		= .FALSE.
				DO_SPECIES % DO_SO2 		= .TRUE.
				DO_SPECIES % DO_HNO3		= .FALSE.
				DO_SPECIES % DO_N2O 		= .FALSE.
				DO_SPECIES % DO_TSUR 		= .FALSE.
				DO_SPECIES % DO_ALL 		= .FALSE.			
				DO_SPECIES % DO_NONE 		= .FALSE.			
			CASE ("HNO3")
				DO_SPECIES % DO_TEMPERATURE = .FALSE.
				DO_SPECIES % DO_H2O 		= .FALSE.
				DO_SPECIES % DO_CO2 		= .FALSE.
				DO_SPECIES % DO_O3 			= .FALSE.
				DO_SPECIES % DO_CO 			= .FALSE.
				DO_SPECIES % DO_CH4 		= .FALSE.
				DO_SPECIES % DO_SO2 		= .FALSE.
				DO_SPECIES % DO_HNO3		= .TRUE.
				DO_SPECIES % DO_N2O 		= .FALSE.
				DO_SPECIES % DO_TSUR 		= .FALSE.
				DO_SPECIES % DO_ALL 		= .FALSE.			
				DO_SPECIES % DO_NONE 		= .FALSE.			
			CASE ("N2O")
				DO_SPECIES % DO_TEMPERATURE = .FALSE.
				DO_SPECIES % DO_H2O 		= .FALSE.
				DO_SPECIES % DO_CO2 		= .FALSE.
				DO_SPECIES % DO_O3 			= .FALSE.
				DO_SPECIES % DO_CO 			= .FALSE.
				DO_SPECIES % DO_CH4 		= .FALSE.
				DO_SPECIES % DO_SO2 		= .FALSE.
				DO_SPECIES % DO_HNO3		= .FALSE.
				DO_SPECIES % DO_N2O 		= .TRUE.
				DO_SPECIES % DO_TSUR 		= .FALSE.
				DO_SPECIES % DO_ALL 		= .FALSE.			
				DO_SPECIES % DO_NONE 		= .FALSE.			
			CASE ('TSUR') ! Equivalent to "NONE" for now
				DO_SPECIES % DO_TEMPERATURE = .FALSE.
				DO_SPECIES % DO_H2O 		= .FALSE.
				DO_SPECIES % DO_CO2 		= .FALSE.
				DO_SPECIES % DO_O3 			= .FALSE.
				DO_SPECIES % DO_CO 			= .FALSE.
				DO_SPECIES % DO_CH4 		= .FALSE.
				DO_SPECIES % DO_SO2 		= .FALSE.
				DO_SPECIES % DO_HNO3		= .FALSE.
				DO_SPECIES % DO_N2O 		= .FALSE.
				DO_SPECIES % DO_TSUR 		= .TRUE.
				DO_SPECIES % DO_ALL 		= .FALSE.			
				DO_SPECIES % DO_NONE 		= .TRUE.			
			CASE ('NONE') ! Return all saved predictors and multipliers without making any new calculations
				DO_SPECIES % DO_TEMPERATURE = .FALSE.
				DO_SPECIES % DO_H2O 		= .FALSE.
				DO_SPECIES % DO_CO2 		= .FALSE.
				DO_SPECIES % DO_O3 			= .FALSE.
				DO_SPECIES % DO_CO 			= .FALSE.
				DO_SPECIES % DO_CH4 		= .FALSE.
				DO_SPECIES % DO_SO2 		= .FALSE.
				DO_SPECIES % DO_HNO3		= .FALSE.
				DO_SPECIES % DO_N2O 		= .FALSE.
				DO_SPECIES % DO_TSUR 		= .FALSE.
				DO_SPECIES % DO_ALL 		= .FALSE.			
				DO_SPECIES % DO_NONE 		= .TRUE.			
			CASE DEFAULT
				DO_SPECIES % DO_TEMPERATURE = .TRUE.
				DO_SPECIES % DO_H2O 		= .TRUE.
				DO_SPECIES % DO_CO2 		= .TRUE.
				DO_SPECIES % DO_O3 			= .TRUE.
				DO_SPECIES % DO_CO 			= .TRUE.
				DO_SPECIES % DO_CH4 		= .TRUE.
				DO_SPECIES % DO_SO2 		= .TRUE.
				DO_SPECIES % DO_HNO3 		= .TRUE.
				DO_SPECIES % DO_N2O 		= .TRUE.
				DO_SPECIES % DO_TSUR 		= .TRUE.
				DO_SPECIES % DO_ALL 		= .TRUE.			
				DO_SPECIES % DO_NONE 		= .FALSE.			
		END SELECT CONSTITUENT

		RETURN

	END FUNCTION SELECT_SPECIES__DETERMINE_DO_SPECIES_ARRAY

	FUNCTION SELECT_SPECIES__DO_ALL_SPECIES() RESULT(DO_SPECIES)

		TYPE (DO_SPECIES_LOGICAL_ARRAY_TYPE) :: DO_SPECIES

		! same flags as ALL_NO_SAVE
		DO_SPECIES % DO_TEMPERATURE = .TRUE.
		DO_SPECIES % DO_H2O 		= .TRUE.
		DO_SPECIES % DO_CO2 		= .TRUE.
		DO_SPECIES % DO_O3 			= .TRUE.
		DO_SPECIES % DO_CO 			= .TRUE.
		DO_SPECIES % DO_CH4 		= .TRUE.
		DO_SPECIES % DO_SO2 		= .TRUE.
		DO_SPECIES % DO_HNO3 		= .TRUE.
		DO_SPECIES % DO_N2O 		= .TRUE.
		DO_SPECIES % DO_ALL 		= .FALSE.			
		DO_SPECIES % DO_NONE 		= .FALSE.			

		RETURN

	END FUNCTION SELECT_SPECIES__DO_ALL_SPECIES 

END MODULE SELECT_SPECIES
